[tool.poetry]
name = "webctfchallenge"
version = "0.1.0"
description = ""
authors = ["Lucy Hochkamp <git@xyno.systems>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
